<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_textarea</name>
   <tag></tag>
   <elementGuidId>5c2f6ee8-b26c-4809-9923-ed8f334fa0d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>textarea</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
