<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>page_name</name>
   <tag></tag>
   <elementGuidId>239c13eb-abcc-4610-8d86-518954d6b3cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.page-name</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
