<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>short_wb_page</name>
   <tag></tag>
   <elementGuidId>7df0206c-7929-4e4e-ad99-d61659ac46eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a#qwb</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
