<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>toast_message</name>
   <tag></tag>
   <elementGuidId>d1fd9ab5-3db7-4e8c-9f02-b9b1a675c844</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.Toastify__toast-body.toast-body</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
